### ISSUE TITLE
Dropbox APIs have changed

### ISSUE THREAD

**Issue by Cemil97** [michael5r/mmm-dropbox#4]
[Updates to Dropbox API v10.zip](https://github.com/michael5r/mmm-dropbox/files/8055426/Updates.to.Dropbox.API.v10.zip)
A few months ago this stopped working for me. Got it working again by upgrading to latest Dropbox SDK (10.24.0) and latest isomorphic-fetch (3.0.0.) 

Apparently order of MM notifications has changed (MODULE_DOM_CREATED arrives before DOM_OBJECTS_CREATED) and Dropbox JSON results have new structure.

Updated files attached.

**Comment by michael5r** [comment]
That's awesome, @Cemil97 - very much appreciate the work. I'll release a new version now.
